project:
  type: website
  output-dir: docs
  
website:
  title: "Carlos Llosa"
  search: true
  navbar:
    right:
      - href: index.qmd
        text: Home
      - papers.qmd
      - presentations.qmd
      - software.qmd
      - icon: github
        url: "https://github.com/carlos-llosa"
      - icon: linkedin
        url: "https://www.linkedin.com/in/carlos-llosa-83a77aa2/"
      - icon: google
        url: "https://scholar.google.com/citations?hl=en&user=NsKKWZcAAAAJ"

format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual